-- ============================================================
-- Migration 002: Composite Performance Indexes & Fulltext Search
-- Leave Management System
-- ============================================================
--
-- These indexes dramatically improve query performance on the
-- most common WHERE / JOIN / ORDER clauses used by the application.
-- They are not auto-generated by Sequelize model definitions and
-- must be applied separately.
--
-- NOTE: MySQL does not support CREATE INDEX IF NOT EXISTS.
-- The migration runner catches 'Duplicate key name' errors
-- and skips them gracefully, so plain CREATE INDEX is used.
-- ============================================================

-- Leave requests: most frequent queries filter by employee + status + date range
-- Used in: employee dashboard, leave request listing with filters
-- Skip if already exists (caught by migration runner error handler)
CREATE INDEX `idx_leave_requests_employee_status_dates`
  ON `leave_requests` (`employeeId`, `status`, `startDate`, `endDate`);

-- Leave requests: admin queries by status + date range
-- Used in: admin leave request listing, reports
CREATE INDEX `idx_leave_requests_status_date_range`
  ON `leave_requests` (`status`, `startDate`, `endDate`);

-- Leave balances: per employee per year (used in dashboard & enforcement)
-- Used in: employee dashboard, leave credit page, balance validation
CREATE INDEX `idx_leave_balances_employee_year`
  ON `leave_balances` (`employeeId`, `year`);

-- Employees: fulltext indexes for search across name and email
-- Used in: employee search bar, global search
ALTER TABLE `employees`
  ADD FULLTEXT INDEX `ft_employees_name_search` (`firstName`, `lastName`, `email`);

-- Departments: fulltext index for name search
-- Used in: department search/filter
ALTER TABLE `departments`
  ADD FULLTEXT INDEX `ft_departments_name` (`name`);
